version: '3'
services:
  # nginx: 
  #   restart: always
  #   build: 
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports: 
  #     - '3050:80'
  #   depends_on:
  #     - api
  #     - client
  # postgres:
  #   image: 'postgres:latest'
  # api:
  #   build: 
  #     dockerfile: Dockerfile.dev
  #     context: ./api
  #   volumes: 
  #     - /app/node_modules
  #     - ./api:/app
  #   environment:
  #     - PGUSER=postgres
  #     - PGHOST=postgres
  #     - PGDATABASE=postgres
  #     - PGPASSWORD=postgres_password
  #     - PGPORT=5432
  #   depends_on:
  #     - postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'